#!/bin/sh
cd /home/buechner/isimip_iplex/data/BC_ISIMIP2/BC_routines
. exports

gdl <<EOF
.r period.pro
.r runidx.pro
.r gdl_exports
.r definitions/definitions_generic.pro
.r definitions/definitions_internal_generic.pro
.r gdl_routines/generic/functions.pro
mon = _MON_GDL_
.r gdl_routines/$BC_VERSION/apply_P_cor_mon.pro
exit
EOF

# remove main script lock
rm apply_P_cor_mon_MON_FILE_.*
