#!/bin/sh
cd _WRKDIR_
. exports

gdl <<EOF
.r period.pro
.r runidx.pro
.r gdl_exports
.r definitions/definitions_generic.pro
.r definitions/definitions_internal_generic.pro
.r gdl_routines/generic/functions.pro
mon = _MON_GDL_
.r gdl_routines/$BC_VERSION/apply_O_cor_mon.pro
exit
EOF


# remove main script lock
rm apply_O_cor_mon_MON_FILE_.*
