#!/bin/bash
cd _WRKDIR_
. exports

gdl <<EOF
.r period.pro
.r runidx.pro
.r gdl_exports
.r definitions/definitions_generic.pro
.r definitions/definitions_internal_generic.pro
.r gdl_routines/generic/functions.pro
mon = _MON_GDL_
.r gdl_routines/$BC_VERSION/calc_T_cor_coeff_mon.pro
exit
EOF

# remove main script lock
rm construct_T_cor_mon_MON_FILE_.*
