#!/bin/bash
cd /home/buechner/isimip_iplex/data/BC_ISIMIP2/BC_routines
. exports

gdl <<EOF
.r period.pro
.r runidx.pro
.r gdl_exports
.r definitions_generic.pro
.r definitions_internal_generic.pro
.r gdl_routines/generic/functions.pro
mon = _MON_
.r gdl_routines/$BC_VERSION/calc_T_cor_coeff_mon.pro
exit
EOF

# remove main script lock
rm construct_T_cor_mon$((_MON_ + 1)).*
